baseURL = "https://wm4n.github.io/nano-banana-prompt/"
languageCode = "en-us"
title = "Image Gen Prompts"

[taxonomies]
  tag = "tags"

[params]
  description = "AI image generation prompts gallery"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
  pagerSize = 200
